<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.faizarfi</groupId>
        <artifactId>starter-arfi-id-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>arfi-id-spring-boot-starter</artifactId>
    <name>Arfi ID Spring Boot Starter</name>
    <description>Aggregator starter for Arfi ID client integration</description>

    <dependencies>
        <dependency>
            <groupId>dev.faizarfi</groupId>
            <artifactId>arfi-id-spring-boot-autoconfigure</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>